name: go-test
on:
    push:
      branches:
        - master
        - develop
    pull_request:

permissions:
    contents: read
    # Optional: allow read access to pull request. Use with `only-new-issues` option.
    # pull-requests: read

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest  # Specify the runner environment
    
        steps:
        - name: Checkout code
        uses: actions/checkout@v2  # If you're using GitHub Actions
    cle
        uses: actions/setup-go@v4
        with:
            go-version: '1.21'  # Specify your Go version
    
        - name: Build
        run: go build -v ./...
    
        - name: Test
        run: go test -v ./...
